### ISSUE TITLE
QProcess is not defined

### ISSUE THREAD

**Issue by ddeityy** [HammyHavoc/GlucoseMonitorKDEWidget#1]
Hey, I saw your reddit post from a couple months ago and was wondering if the widget is unfinished or it's a problem on my end.

When starting the widget with or without setting the URL and token it errors out with
```ReferenceError: QProcess is not defined```
and gets stuck on
```Testing command execution...```

I tried playing around with the source code but nothing worked, maybe I'm missing some weird KDE dependency?

**Comment by HammyHavoc** [comment]
Still twiddling away! Expecting to have it done in the next week or so. :- )

I changed my approach and increased the overall scope (optional notifications for high/low alarms, switchable units, logging COB, few other cute tricks).

**Comment by ddeityy** [comment]
I see, thanks for such a quick response.
I started looping this week and was almost ready to try writing a widget myself or porting an old one to plasma6.
But man, the documentation for plasma 6 is awful.
